import type { Sim } from './engine'
import type { Rng } from './rng'
import type { Request, Sink } from './types'

/**
 * Time-varying arrival rate (requests per time unit). `max` bounds the rate
 * so arrivals can be generated by thinning a homogeneous Poisson process.
 */
export type Rate = ((t: number) => number) & { max: number }

function rate(fn: (t: number) => number, max: number): Rate {
  return Object.assign(fn, { max })
}

export const constant = (lambda: number): Rate => rate(() => lambda, lambda)

export const step = (t0: number, before: number, after: number): Rate =>
  rate((t) => (t < t0 ? before : after), Math.max(before, after))

/** Linear ramp from `from` at t0 to `to` at t1, flat outside. */
export const ramp = (t0: number, t1: number, from: number, to: number): Rate =>
  rate((t) => {
    if (t <= t0) return from
    if (t >= t1) return to
    return from + ((to - from) * (t - t0)) / (t1 - t0)
  }, Math.max(from, to))

/**
 * Logistic (S-curve) ramp from `from` to `to` over [t0, t0 + duration]:
 * midpoint at t0 + duration/2, ~1% / 99% at the ends.
 */
export const logistic = (t0: number, duration: number, from: number, to: number): Rate => {
  const mid = t0 + duration / 2
  const k = 2 * Math.log(99) / duration
  return rate((t) => from + (to - from) / (1 + Math.exp(-k * (t - mid))), Math.max(from, to))
}

/** Extra `extra` req/s during [t0, t0 + duration). */
export const spike = (t0: number, duration: number, extra: number): Rate =>
  rate((t) => (t >= t0 && t < t0 + duration ? extra : 0), extra)

export const sum = (...rates: Rate[]): Rate =>
  rate((t) => rates.reduce((s, r) => s + r(t), 0), rates.reduce((s, r) => s + r.max, 0))

/** Non-homogeneous Poisson arrivals via thinning. */
export class Arrivals {
  private nextId = 0
  private running = false

  constructor(private sim: Sim, private rng: Rng, private rate: Rate, private sink: Sink) {}

  start(): void {
    this.running = true
    this.scheduleNext()
  }

  stop(): void {
    this.running = false
  }

  private scheduleNext(): void {
    const max = this.rate.max
    if (max <= 0) return
    this.sim.schedule(this.rng.exp(max), () => {
      if (!this.running) return
      if (this.rng.next() < this.rate(this.sim.now) / max) {
        const req: Request = { id: this.nextId++, arrivedAt: this.sim.now }
        this.sink(req)
      }
      this.scheduleNext()
    })
  }
}
